include: package:runtime_common_codestyle/recommended.yaml

formatter:
  page_width: 80

analyzer:
  errors:
    avoid_print: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mappable.dart"

