// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'keybinds_config.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

KeybindsConfig _$KeybindsConfigFromJson(Map<String, dynamic> json) => KeybindsConfig(
  sessionChildCycle: json['session_child_cycle'] as String? ?? 'ctrl+right',
  appHelp: json['app_help'] as String? ?? '<leader>h',
  appExit: json['app_exit'] as String? ?? 'ctrl+c,<leader>q',
  editorOpen: json['editor_open'] as String? ?? '<leader>e',
  themeList: json['theme_list'] as String? ?? '<leader>t',
  projectInit: json['project_init'] as String? ?? '<leader>i',
  toolDetails: json['tool_details'] as String? ?? '<leader>d',
  thinkingBlocks: json['thinking_blocks'] as String? ?? '<leader>b',
  sessionExport: json['session_export'] as String? ?? '<leader>x',
  sessionNew: json['session_new'] as String? ?? '<leader>n',
  sessionList: json['session_list'] as String? ?? '<leader>l',
  sessionTimeline: json['session_timeline'] as String? ?? '<leader>g',
  sessionShare: json['session_share'] as String? ?? '<leader>s',
  sessionUnshare: json['session_unshare'] as String? ?? 'none',
  sessionInterrupt: json['session_interrupt'] as String? ?? 'esc',
  sessionCompact: json['session_compact'] as String? ?? '<leader>c',
  leader: json['leader'] as String? ?? 'ctrl+x',
  sessionChildCycleReverse: json['session_child_cycle_reverse'] as String? ?? 'ctrl+left',
  messagesPageUp: json['messages_page_up'] as String? ?? 'pgup',
  messagesPageDown: json['messages_page_down'] as String? ?? 'pgdown',
  messagesHalfPageUp: json['messages_half_page_up'] as String? ?? 'ctrl+alt+u',
  messagesHalfPageDown: json['messages_half_page_down'] as String? ?? 'ctrl+alt+d',
  messagesFirst: json['messages_first'] as String? ?? 'ctrl+g',
  messagesLast: json['messages_last'] as String? ?? 'ctrl+alt+g',
  messagesCopy: json['messages_copy'] as String? ?? '<leader>y',
  messagesUndo: json['messages_undo'] as String? ?? '<leader>u',
  messagesRedo: json['messages_redo'] as String? ?? '<leader>r',
  modelList: json['model_list'] as String? ?? '<leader>m',
  modelCycleRecent: json['model_cycle_recent'] as String? ?? 'f2',
  modelCycleRecentReverse: json['model_cycle_recent_reverse'] as String? ?? 'shift+f2',
  agentList: json['agent_list'] as String? ?? '<leader>a',
  agentCycle: json['agent_cycle'] as String? ?? 'tab',
  messagesRevert: json['messages_revert'] as String? ?? 'none',
  inputClear: json['input_clear'] as String? ?? 'ctrl+c',
  inputPaste: json['input_paste'] as String? ?? 'ctrl+v',
  inputSubmit: json['input_submit'] as String? ?? 'enter',
  inputNewline: json['input_newline'] as String? ?? 'shift+enter,ctrl+j',
  switchMode: json['switch_mode'] as String? ?? 'none',
  switchModeReverse: json['switch_mode_reverse'] as String? ?? 'none',
  switchAgent: json['switch_agent'] as String? ?? 'tab',
  switchAgentReverse: json['switch_agent_reverse'] as String? ?? 'shift+tab',
  fileList: json['file_list'] as String? ?? 'none',
  fileClose: json['file_close'] as String? ?? 'none',
  fileSearch: json['file_search'] as String? ?? 'none',
  fileDiffToggle: json['file_diff_toggle'] as String? ?? 'none',
  messagesPrevious: json['messages_previous'] as String? ?? 'none',
  messagesNext: json['messages_next'] as String? ?? 'none',
  messagesLayoutToggle: json['messages_layout_toggle'] as String? ?? 'none',
  agentCycleReverse: json['agent_cycle_reverse'] as String? ?? 'shift+tab',
);

Map<String, dynamic> _$KeybindsConfigToJson(KeybindsConfig instance) => <String, dynamic>{
  'leader': instance.leader,
  'app_help': instance.appHelp,
  'app_exit': instance.appExit,
  'editor_open': instance.editorOpen,
  'theme_list': instance.themeList,
  'project_init': instance.projectInit,
  'tool_details': instance.toolDetails,
  'thinking_blocks': instance.thinkingBlocks,
  'session_export': instance.sessionExport,
  'session_new': instance.sessionNew,
  'session_list': instance.sessionList,
  'session_timeline': instance.sessionTimeline,
  'session_share': instance.sessionShare,
  'session_unshare': instance.sessionUnshare,
  'session_interrupt': instance.sessionInterrupt,
  'session_compact': instance.sessionCompact,
  'session_child_cycle': instance.sessionChildCycle,
  'session_child_cycle_reverse': instance.sessionChildCycleReverse,
  'messages_page_up': instance.messagesPageUp,
  'messages_page_down': instance.messagesPageDown,
  'messages_half_page_up': instance.messagesHalfPageUp,
  'messages_half_page_down': instance.messagesHalfPageDown,
  'messages_first': instance.messagesFirst,
  'messages_last': instance.messagesLast,
  'messages_copy': instance.messagesCopy,
  'messages_undo': instance.messagesUndo,
  'messages_redo': instance.messagesRedo,
  'model_list': instance.modelList,
  'model_cycle_recent': instance.modelCycleRecent,
  'model_cycle_recent_reverse': instance.modelCycleRecentReverse,
  'agent_list': instance.agentList,
  'agent_cycle': instance.agentCycle,
  'agent_cycle_reverse': instance.agentCycleReverse,
  'input_clear': instance.inputClear,
  'input_paste': instance.inputPaste,
  'input_submit': instance.inputSubmit,
  'input_newline': instance.inputNewline,
  'switch_mode': instance.switchMode,
  'switch_mode_reverse': instance.switchModeReverse,
  'switch_agent': instance.switchAgent,
  'switch_agent_reverse': instance.switchAgentReverse,
  'file_list': instance.fileList,
  'file_close': instance.fileClose,
  'file_search': instance.fileSearch,
  'file_diff_toggle': instance.fileDiffToggle,
  'messages_previous': instance.messagesPrevious,
  'messages_next': instance.messagesNext,
  'messages_layout_toggle': instance.messagesLayoutToggle,
  'messages_revert': instance.messagesRevert,
};
