/// https://dart.dev/language/keywords
/// Set of keywords to check for the variable name
const _dartKeywords = {
  'abstract',
  'as',
  'assert',
  'async',
  'await',
  'base',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'covariant',
  'default',
  'deferred',
  'do',
  'dynamic',
  'else',
  'enum',
  'export',
  'extends',
  'extension',
  'external',
  'factory',
  'false',
  'final',
  'finally',
  'for',
  'function',
  'get',
  'hashCode',
  'hide',
  'if',
  'implements',
  'import',
  'in',
  'interface',
  'is',
  'late',
  'library',
  'mixin',
  'new',
  'null',
  'on',
  'operator',
  'part',
  'required',
  'rethrow',
  'return',
  'sealed',
  'set',
  'show',
  'static',
  'super',
  'switch',
  'sync',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'var',
  'void',
  'when',
  'while',
  'with',
  'yield',
};

/// Reserved field names - field names that conflict with Dart built-in types
/// Fields with these names will get "Field" suffix
const reservedFieldNames = {
  ..._dartKeywords,
  'int',
  'double',
  'num',
  'bool',
  'object',
  'values',
  'index',
  'toString',
  'runtimeType',
  'noSuchMethod',
  'json',
  'self',
  // Note: 'list' and 'map' are valid Dart identifiers and should NOT be reserved.
  // They were temporarily added but removed as they unnecessarily rename parameters.
  // 'set' is already in _dartKeywords
};

/// Reserved class names - class names that conflict with generated code or libraries
/// Classes with these names will get "Model" suffix
/// All names are stored in lowercase for case-insensitive comparison
const reservedClassNames = {
  // Dart built-in types
  'String',
  'Object',
  'List',
  'Set',
  'Map',

  // Dio types
  'Response',
  'Requestoptions',
  'Options',
  'Dio',
  'MultipartFile',
  'CancelToken',
  'DioException',
  'DioError',
  'FormData',
  'ProgressCallback',
  'Interceptor',
  'InterceptorsWrapper',

  // Retrofit annotation types
  'Field',
  'Body',
  'Query',
  'Path',
  'Header',
  'Part',
  'PartMap',
  'Queries',
  'Headers',
  'Get',
  'Post',
  'Put',
  'Delete',
  'Patch',
  'Head',
  'Method',
  'Extra',
  'CacheControl',
  'DioResponseType',
  'HttpResponse',

  // Common schema type names that conflict with generated code
  'Array',
  'Enum',
  'Primitive',
  'DateTime',
  'Uri',
  'Symbol',
  'Type',
};
